### ISSUE TITLE
TU throws erros

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#13]
Add a new TU, in this case its my first TU for the project, then select a parent, throws error below

**Comment by robertallanroker** [comment]
Uncaught Error: KeyError: 'id'
http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1585
Traceback:
Error: KeyError: 'id'
    at F.__getitem__ (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1585:161)
    at F.__getattr__ (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1586:69)
    at F.__getattribute__ (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1385:38)
    at Object.py.PY_getAttr (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1349:176)
    at Object.py.evaluate (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1452:11)
    at Object.py.evaluate (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1447:111)
    at Object.py.evaluate (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1449:99)
    at Object.py.eval (http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1454:284)
    at http://localhost:8069/web/content/292-6c6836b/web.assets_backend.js:1596:136
    at Function._.each._.forEach (http://localhost:8069/web/content/251-faa316f/web.assets_common.js:12:558)

**Comment by odoosocius** [comment]
Error not found
