### ISSUE TITLE
Module Produces an install error - does not install

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#2]
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo-10.0/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-10.0/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-10.0/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 639, in _tag_record
    self._test_xml_id(rec_id)
  File "/opt/odoo/odoo-10.0/odoo/tools/convert.py", line 251, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
ParseError: "The ID "sales_team.menu_base_partner" refers to an uninstalled module" while parsing /opt/odoo/green_project/inh.xml:75, near
<record model="ir.ui.menu" id="sales_team.menu_base_partner">

          <field name="groups_id" eval="[(6, 0, [ref('group_hide_menus')])]"/>
        </record>

**Comment by robertallanroker** [comment]
I can install the module if i first add the CRM and SALES module.  The R&D module needs to stand alone with just the Projects and Time Recording functionality.

**Comment by robertallanroker** [comment]
Install a new ODOO database with no other modules activated, then install the R-D tool to observe the dependency error.

**Comment by robertallanroker** [comment]
Latest error on install,
Traceback (most recent call last):
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 697, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 138, in _eval_xml
    +_process("".join([etree.tostring(n, encoding='utf-8') for n in node]))
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 130, in _process
    self.idref[id] = self.id_get(id)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 782, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 788, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-28>", line 2, in xmlid_lookup
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: greenlight.experiment_form55" while parsing /Users/rroker/odoodev/dev/rd-tool/views/project_kanban.xml:3, near
<record id="inherited_kanban_form" model="ir.ui.view">
        <field name="model">project.project</field>
        <field name="inherit_id" ref="project.view_project_kanban"/>
        <field name="arch" type="xml">
            <xpath expr="//kanban[@class='oe_background_grey o_kanban_dashboard o_project_kanban']" position="replace">
                <kanban class="oe_background_grey o_kanban_dashboard o_project_kanban">
                    <field name="name"/>
                    <field name="use_tasks"/>
                    <field name="color"/>
                    <field name="task_count"/>
                    <field name="task_needaction_count"/>
                    <field name="label_tasks"/>
                    <field name="alias_id"/>
                    <field name="alias_name"/>
                    <field name="alias_domain"/>
                    <field name="doc_count"/>
                    <field name="is_favorite"/>
                    <templates>
                        <t t-name="kanban-box">
                            <div t-attf-class="#{kanban_color(record.color.raw_value)} oe_kanban_global_click">
                                <div class="o_project_kanban_main">
                                    <a type="edit">
                                        <div class="o_kanban_card_content o_visible">
                                            <div class="o_kanban_primary_left">
                                                <div class="o_primary">
                                                    <span>Project name :                                                                                                                                                                                                                            
                                                        <t t-esc="record.name.value"/>
                                                    </span>
                                                </div>
                                            </div>
                                            <div t-if="record.alias_name.value and record.alias_domain.value">
                                                <span>
                                                    <i class="fa fa-envelope"/>
                                                    <t t-esc="record.alias_id.value"/>
                                                </span>
                                            </div>
                                        </div>
                                    </a>
                                    <a type="edit">
                                        <div class="o_kanban_card_manage_pane o_invisible">
                                            <div class="o_kanban_card_manage_section o_kanban_manage_reports">
                                                <div groups="project.group_project_manager">
                                                    <a type="edit">Settings</a>
                                                </div>
                                                <div>
                                                    <a name="%(greenlight.experiment_form55)d" type="action">experiment</a>
                                                </div>
                                                <div>
                                                    <a name="%(greenlight.uncertinity56)d" type="action">Uncertinites</a>
                                                </div>
                                            </div>
                                            <div t-if="widget.editable" class="o_project_kanban_colorpicker">
                                                <ul class="oe_kanban_colorpicker" data-field="color"/>
                                            </div>
                                        </div>
                                        <div class="o_project_kanban_manage">
                                            <a class="o_kanban_manage_toggle_button o_left" href="#">More                                                                                                                                                 
                                                <i class="fa fa-caret-down"/>
                                            </a>
                                            <a type="object" name="toggle_favorite" class="o_right">
                                                <i t-attf-class="oe_inline fa o_dashboard_star #{record.is_favorite.raw_value ? 'fa-star' : 'fa-star-o'}" title="Add/remove from favorite"/>
                                            </a>
                                        </div>
                                    </a>
                                </div>
                                <div class="o_project_kanban_boxes">
                                    <div t-if="record.doc_count.raw_value" class="o_project_kanban_box">
                                        <a name="attachment_tree_view" type="object">
                                            <span class="o_value">
                                                <t t-esc="record.doc_count.value"/>
                                            </span>
                                            <span class="o_label">Documents</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </t>
                    </templates>
                </kanban>
            </xpath>
        </field>
    </record>**

**Comment by robertallanroker** [comment]
Traceback (most recent call last):
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 697, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 138, in _eval_xml
    +_process("".join([etree.tostring(n, encoding='utf-8') for n in node]))
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 130, in _process
    self.idref[id] = self.id_get(id)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 782, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 788, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-28>", line 2, in xmlid_lookup
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: greenlight.experiment_form55" while parsing /Users/rroker/odoodev/dev/rd-tool/views/project_kanban.xml:3, near
<record id="inherited_kanban_form" model="ir.ui.view">
        <field name="model">project.project</field>
        <field name="inherit_id" ref="project.view_project_kanban"/>
        <field name="arch" type="xml">
            <xpath expr="//kanban[@class='oe_background_grey o_kanban_dashboard o_project_kanban']" position="replace">
                <kanban class="oe_background_grey o_kanban_dashboard o_project_kanban">
                    <field name="name"/>
                    <field name="use_tasks"/>
                    <field name="color"/>
                    <field name="task_count"/>
                    <field name="task_needaction_count"/>
                    <field name="label_tasks"/>
                    <field name="alias_id"/>
                    <field name="alias_name"/>
                    <field name="alias_domain"/>
                    <field name="doc_count"/>
                    <field name="is_favorite"/>
                    <templates>
                        <t t-name="kanban-box">
                            <div t-attf-class="#{kanban_color(record.color.raw_value)} oe_kanban_global_click">
                                <div class="o_project_kanban_main">
                                    <a type="edit">
                                        <div class="o_kanban_card_content o_visible">
                                            <div class="o_kanban_primary_left">
                                                <div class="o_primary">
                                                    <span>Project name :                                                                                                                                                                                                                            
                                                        <t t-esc="record.name.value"/>
                                                    </span>
                                                </div>
                                            </div>
                                            <div t-if="record.alias_name.value and record.alias_domain.value">
                                                <span>
                                                    <i class="fa fa-envelope"/>
                                                    <t t-esc="record.alias_id.value"/>
                                                </span>
                                            </div>
                                        </div>
                                    </a>
                                    <a type="edit">
                                        <div class="o_kanban_card_manage_pane o_invisible">
                                            <div class="o_kanban_card_manage_section o_kanban_manage_reports">
                                                <div groups="project.group_project_manager">
                                                    <a type="edit">Settings</a>
                                                </div>
                                                <div>
                                                    <a name="%(greenlight.experiment_form55)d" type="action">experiment</a>
                                                </div>
                                                <div>
                                                    <a name="%(greenlight.uncertinity56)d" type="action">Uncertinites</a>
                                                </div>
                                            </div>
                                            <div t-if="widget.editable" class="o_project_kanban_colorpicker">
                                                <ul class="oe_kanban_colorpicker" data-field="color"/>
                                            </div>
                                        </div>
                                        <div class="o_project_kanban_manage">
                                            <a class="o_kanban_manage_toggle_button o_left" href="#">More                                                                                                                                                 
                                                <i class="fa fa-caret-down"/>
                                            </a>
                                            <a type="object" name="toggle_favorite" class="o_right">
                                                <i t-attf-class="oe_inline fa o_dashboard_star #{record.is_favorite.raw_value ? 'fa-star' : 'fa-star-o'}" title="Add/remove from favorite"/>
                                            </a>
                                        </div>
                                    </a>
                                </div>
                                <div class="o_project_kanban_boxes">
                                    <div t-if="record.doc_count.raw_value" class="o_project_kanban_box">
                                        <a name="attachment_tree_view" type="object">
                                            <span class="o_value">
                                                <t t-esc="record.doc_count.value"/>
                                            </span>
                                            <span class="o_label">Documents</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </t>
                    </templates>
                </kanban>
            </xpath>
        </field>
    </record>

**Comment by robertallanroker** [comment]
Traceback (most recent call last):
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 697, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 138, in _eval_xml
    +_process("".join([etree.tostring(n, encoding='utf-8') for n in node]))
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 130, in _process
    self.idref[id] = self.id_get(id)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 782, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 788, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-28>", line 2, in xmlid_lookup
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: greenlight.experiment_form55" while parsing /Users/rroker/odoodev/dev/rd-tool/views/project_kanban.xml:3, near
