### ISSUE TITLE
Cant Install Latest Version

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#23]
Traceback (most recent call last):
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/rroker/odoodev/odoo-10/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/rroker/odoodev/odoo-10/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/Users/rroker/odoodev/odoo-10/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 639, in _tag_record
    self._test_xml_id(rec_id)
  File "/Users/rroker/odoodev/odoo-10/odoo/tools/convert.py", line 251, in _test_xml_id
    assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
ParseError: "The ID "utm.menu_link_tracker_root" refers to an uninstalled module" while parsing /Users/rroker/odoodev/dev/rd-tool/rd_tool/views/project_menu_hide.xml:35, near
<record model="ir.ui.menu" id="utm.menu_link_tracker_root">
      <field name="groups_id" eval="[(6, 0, [ref('group_hide_menus')])]"/>
    </record>

**Comment by odoosocius** [comment]
Issue is fixed, it happened because one additional module was already installed in our local system which is not present on the server.
