### ISSUE TITLE
Functional Issues

### ISSUE THREAD

**Issue by robertallanroker** [GreenlightIP/rd-tool#32]
# Projects Form
## Start and End Dates
Do we need to make these two fields mandatory?
## RD Flag user change
Good: Warning message appears when flag goes from ON to OFF, however, flag remains OFF after warning and has instructed users to remove R&D elements, which visually has now disappeared.
Solution, For now, if R&D is set, and there are running experiments, disallow the change. We will address the issue of how to do this later.
## Technical Advancements (TAB)
- [ ] Technical Advancements Show TU's *great*, TU's should be color coded by status
- [ ] We allow TU's to be created on the FLY with advancement, but it is important that each TU we answer the eligibility questions to determine SR&ED or NOT.  Hence, lets disallow creating new TU's from within the list.
- [ ] Lets change the TU widget in this list to a multi-check box drop down
## Technical Uncertainties (TAB)
List of TUs does not grow as you assign them in the TA's tab
## Add Item from list opens TU (Form)
- [ ] Allow users to multi-check box associated advancements if they like
- [ ] Click (True|False) Experimentation Required, which does update Eligibility Status, however, if the risk %0 it shold not currently have SR&ED eligibility.  
- [ ] Lets default Risk % to 100% on new records, this we help in Experimentation Required changes
- [ ] We should prompt user, warn them, if you click Experimentation Required and Risk is %0.00 - ask them if correct as this makes uncertainty currently not eligible.  Shall we fix this?  Yes, bump to 100%
- [ ] Why_is experimentation Required Tab/Field, should be first before remarks
- [ ] User must write something in the box, error validation, Lets also put a word limit on it. for now lets say there must be at least a 100 word count limit.  We would need to display the limit in the UI interface so that users will know.
# Experiments Form
- [ ] Users can not add Systematic Investigations
- [ ] Advancing to next interval generates an assertion error
`Traceback (most recent call last):
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/rroker/odoodev/odoo-11/odoo/tools/pycompat.py", line 86, in reraise
    raise value
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 929, in __call__
    return self.method(*args, **kw)
  File "/Users/rroker/odoodev/odoo-11/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/Users/rroker/odoodev/odoo-11/addons/web/controllers/main.py", line 920, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/rroker/odoodev/odoo-11/addons/web/controllers/main.py", line 908, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/rroker/odoodev/odoo-11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/rroker/odoodev/odoo-11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/rroker/odoodev/dev/rd-tool/rd_tool/models/rd_tool.py", line 283, in advance_interval
    self.to_date) + timedelta(days=1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'`

**Comment by odoosocius** [comment]
Start and End Dates

Do we need to make these two fields mandatory?
It is made mandatory for the logic that an experiment start date should be between project start and end_date
Advancing to next interval generates an assertion error
This happens when to_date is not set in experiment form which may not happen after last update because start date is mandatory and from date and to date is set automatically on start of first interval
